# Trigger the pipeline to run on changes to the 'main' branch
trigger:
  branches:
    include:
      - main

# Define the build agent pool to use
pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image provided by Microsoft

# Define the sequence of steps to execute
steps:
  - script: |
      npm install    # Install project dependencies listed in package.json
      npm test       # Run the tests defined in your project (commonly uses Jest, Mocha, etc.)
    displayName: 'Install Dependencies and Run Tests'  # Friendly name shown in pipeline logs
